"""Regenerates src/Projectile.txt: every module the projectile system needs,
concatenated verbatim into one read-only file. Run from anywhere:

    python tools/bundle_projectile.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "Projectile.txt"

# Dependency order: foundations, shared motion/protocol, server, client.
SECTIONS = [
    ("Shared foundations", [
        "src/shared/SafeMath.luau",
        "src/shared/Signal.luau",
        "src/shared/Heartbeat.luau",
        "src/shared/VisualOffload.luau",
        "src/shared/ChunkManager.luau",
        "src/shared/Entity.luau",
    ]),
    ("Shared projectile motion and protocol", [
        "src/shared/ProjectileMotion.luau",
        "src/shared/ProjectileStepPlanner.luau",
        "src/shared/ProjectileProtocol.luau",
        "src/shared/ProjectileCodec.luau",
        "src/shared/Projectile/BeamPath.luau",
    ]),
    ("Server simulation", [
        "src/server/Projectile/Types.luau",
        "src/server/Projectile/Config.luau",
        "src/server/Projectile/Math.luau",
        "src/server/Projectile/Raycast.luau",
        "src/server/Projectile/Occupancy.luau",
        "src/server/Projectile/Homing.luau",
        "src/server/Projectile/RewindHit.luau",
        "src/server/Projectile/Replication.luau",
        "src/server/Projectile/Store.luau",
        "src/server/Projectile/Spec.luau",
        "src/server/Projectile/Sweep.luau",
        "src/server/Projectile/Profile.luau",
        "src/server/Projectile/Parallel.luau",
        "src/server/Projectile/init.luau",
        "src/server/Projectile/BeamProjectileHandler.luau",
        "src/server/ProjectileQuota.luau",
        "src/server/ProjectileWorkerBootstrap.server.luau",
    ]),
    ("Client prediction and visuals", [
        "src/shared/ProjectileClient/Types.luau",
        "src/shared/ProjectileClient/Prediction.luau",
        "src/shared/ProjectileClient/View.luau",
        "src/shared/ProjectileClient/DebugRays.luau",
        "src/shared/ProjectileClient/Impact.luau",
        "src/shared/ProjectileClient/VisualModel.luau",
        "src/shared/ProjectileClient/BeamGeometry.luau",
        "src/shared/ProjectileClient/BeamVisual.luau",
        "src/shared/ProjectileClient/init.luau",
    ]),
]

RULE = "-- " + "=" * 77


def main():
    files = [(section, path) for section, paths in SECTIONS for path in paths]
    texts = {}
    for _, path in files:
        texts[path] = (ROOT / path).read_text(encoding="utf-8").replace("\r\n", "\n").rstrip("\n")

    out = [
        "-- PROJECTILE SYSTEM SUPER-FILE",
        "-- Generated by tools/bundle_projectile.py, which concatenates the current",
        "-- projectile source modules verbatim (plus the shared modules they require).",
        "-- Edit the source modules, not this bundle; rerun the script to refresh it.",
        "--",
        "-- Contents:",
    ]
    for section, paths in SECTIONS:
        out.append(f"--   {section}")
        for path in paths:
            out.append(f"--     {path} ({texts[path].count(chr(10)) + 1} lines)")
    out.append("")

    current = None
    for section, path in files:
        if section != current:
            current = section
            out += [RULE, f"-- SECTION: {section}", RULE, ""]
        out += [RULE, f"-- BEGIN FILE: {path}", RULE, texts[path], RULE, f"-- END FILE: {path}", RULE, ""]

    OUT.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(files)} files, {sum(t.count(chr(10)) + 1 for t in texts.values())} source lines")


main()
